# Generated by Django 5.2.10 on 2026-02-16 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(db_index=True, help_text='Flight identifier (e.g., FireFlight_20211203_052327)', max_length=255, unique=True)),
                ('original_filename', models.CharField(help_text='Original filename when uploaded', max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', help_text='Current status of the processing job', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Processing progress from 0 to 100')),
                ('current_step', models.CharField(blank=True, help_text="Description of current processing step (e.g., 'Unzipping', 'Creating mosaic')", max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_path', models.CharField(help_text='Current file system path', max_length=500)),
                ('uploaded_by_email', models.EmailField(help_text='Email address of the uploader (preserved even if user deleted)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created (file uploaded)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this record was updated')),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When processing actually began', null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, help_text='When processing finished (success or failure)', null=True)),
                ('output_geopackage_path', models.CharField(blank=True, help_text='Path to the output GeoPackage file', max_length=500)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('log_file_path', models.CharField(blank=True, help_text='Path to the processing log file', max_length=500)),
                ('total_images_processed', models.IntegerField(blank=True, help_text='Total number of thermal images processed', null=True)),
                ('hotspots_detected', models.IntegerField(blank=True, help_text='Number of hotspots detected', null=True)),
                ('districts_covered', models.JSONField(blank=True, default=list, help_text='List of DBCA districts covered by this flight')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thermal_processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thermal Processing Job',
                'verbose_name_plural': 'Thermal Processing Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tipapp_ther_status_5257fb_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='tipapp_ther_uploade_366d69_idx'), models.Index(fields=['-created_at'], name='tipapp_ther_created_2e6a0e_idx')],
            },
        ),
    ]
