# Generated by Django 5.2.10 on 2026-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalprocessingjob',
            name='retired_at',
            field=models.DateTimeField(blank=True, help_text='When the job was retired (folder renamed, GeoServer and PostGIS data removed)', null=True),
        ),
        migrations.AlterField(
            model_name='thermalprocessingjob',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETIRED', 'Retired')], db_index=True, default='UPLOADED', help_text='Current status of the processing job', max_length=20),
        ),
    ]
