# Generated by Django 5.2.10 on 2026-03-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipapp', '0002_add_retired_status_and_retired_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermalprocessingjob',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETIRED', 'Retired'), ('RETIRE_QUEUED', 'Retire Queued'), ('RETIRING', 'Retiring'), ('RETIRE_FAILED', 'Retire Failed')], db_index=True, default='UPLOADED', help_text='Current status of the processing job', max_length=20),
        ),
    ]
