# Generated by Django 5.2.10 on 2026-03-23 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipapp', '0003_add_retire_queue_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalprocessingjob',
            name='retired_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the retirement of this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_thermal_processing_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thermalprocessingjob',
            name='retired_by_email',
            field=models.EmailField(blank=True, help_text='Email address of the user who retired this job (preserved even if user deleted)', max_length=254),
        ),
    ]
